RESPONSE_CODE_SUCCESS = 00
RESPONSE_CODE_GENERAL_ERROR = 01
RESPONSE_CODE_INVALID_RESOURCE = 02
RESPONSE_CODE_NETWORK_ERROR = 03
RESPONSE_CODE_PARSE_ERROR = 04


RESPONSE_MESSAGE_SUCCESS = "SUCCESS"
RESPONSE_MESSAGE_GENERAL_ERROR = "Unknown Error"
RESPONSE_MESSAGE_INVALID_RESOURCE = "Invalid resource uri"
RESPONSE_MESSAGE_PARSE_ERROR = "Unable to parse Indianrail.gov.in page"
