RESPONSE_CODE_SUCCESS = 00
RESPONSE_CODE_GENERAL_ERROR = 01
RESPONSE_CODE_INVALID_RESOURCE = 02
RESPONSE_CODE_NETWORK_ERROR = 03


RESPONSE_VALUE_SUCCESS = "SUCCESS"
RESPONSE_VALUE_GENERAL_ERROR = "Unknown Error"
